HDDTest::Disk
std::string HDDTest::Disk::path
Referenced by getName, getPath.
uint64_t HDDTest::Disk::pageSize
uint64_t HDDTest::Disk::extentSize
int HDDTest::Disk::fd
char* HDDTest::Disk::pageBuffer
char* HDDTest::Disk::extentBuffer
std::unordered_map< std::string, Disk * > HDDTest::Disk::disks
Disk * HDDTest::Disk::get(std::string)
returns disk
returns a disk pointer path disk path pointer to disk instance
Referenced by HDDTest::TestScenario::run.
void HDDTest::Disk::readPage(uint64_t)
Referenced by HDDTest::IndexScan::executeTestAlgorithm.
void HDDTest::Disk::readExtent(uint64_t)
Referenced by HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::TransactionLog::executeTestAlgorithm.
void HDDTest::Disk::writePage(uint64_t)
Referenced by HDDTest::IndexWrite::executeTestAlgorithm.
void HDDTest::Disk::writeExtent(uint64_t)
Referenced by HDDTest::TransactionLog::executeTestAlgorithm.
void HDDTest::Disk::del()
void HDDTest::Disk::setPageSize(int)
[brief description]
[long description] size [description]
void HDDTest::Disk::setExtentSize(int)
extent-size-setter
sets the extent size in kb size Size of a extent in kb
std::string HDDTest::Disk::getName()
References path.
Referenced by HDDTest::TestScenario::run.
const std::string& HDDTest::Disk::getPath() const
References path.
Referenced by HDDTest::TestScenario::run.
bool HDDTest::Disk::isValid()
HDDTest::Disk::Disk(std::string)
Disk constructor.
The disk constructor initalizes a disk based on a given path path Disk-path
HDDTest::Disk::~Disk()
void HDDTest::Disk::startup()
speeds up a disk
speeds up a disk and read the 1 GB of data
void HDDTest::Disk::open(std::string)
open a disk
Opens a disk and sets a member variable called path path Disk-path