HDDTest::Relationship
std::vector<struct Extent> HDDTest::Relationship::extents
Referenced by Relationship, addExtent, getNextExtent, getPrevExtent, isNextExtent, getRandomExtent, getRandomPage, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm.
std::string HDDTest::Relationship::name
Referenced by Relationship.
unsigned int HDDTest::Relationship::pagesPerExtent
Referenced by Relationship, getRandomPage, HDDTest::TransactionLog::executeTestAlgorithm.
unsigned int HDDTest::Relationship::pageSizeInKB
Referenced by Relationship, getRandomPage.
uint64_t HDDTest::Relationship::unallocatedExtents
uint64_t HDDTest::Relationship::nextExtent
HDDTest::Relationship::Relationship(std::string, uint64_t, unsigned int, unsigned int)
References name, extents, pagesPerExtent, pageSizeInKB.
HDDTest::Relationship::~Relationship()
void HDDTest::Relationship::addExtent(uint64_t)
References HDDTest::Extent::startKb, HDDTest::Extent::number, extents.
int HDDTest::Relationship::getProbability(uint64_t)
void HDDTest::Relationship::setUnallocatedExtents(uint64_t unallocatedExtents)
uint64_t HDDTest::Relationship::getRandomExtent()
References extents.
uint64_t HDDTest::Relationship::getRandomPage()
References extents, pagesPerExtent, pageSizeInKB.
Referenced by HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm.
uint64_t HDDTest::Relationship::getNextExtent()
References isNextExtent, extents.
Referenced by HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::TransactionLog::executeTestAlgorithm.
uint64_t HDDTest::Relationship::getPrevExtent()
References isNextExtent, extents.
Referenced by HDDTest::TransactionLog::executeTestAlgorithm.
uint64_t HDDTest::Relationship::getNextPage()
bool HDDTest::Relationship::isNextExtent()
References extents.
Referenced by getNextExtent, getPrevExtent, HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::TransactionLog::executeTestAlgorithm.
void HDDTest::Relationship::setNextExtent(uint64_t)
Referenced by HDDTest::TransactionLog::executeTestAlgorithm.