DBUtil::Log
timespec DBUtil::Log::startTime
std::vector<struct measurement>* DBUtil::Log::measurements
DBUtil::Log::Log()
DBUtil::Log::~Log()
void DBUtil::Log::start()
Referenced by HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm.
void DBUtil::Log::stop(uint64_t)
References DBUtil::measurement::size, DBUtil::measurement::duration.
Referenced by HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm.
void DBUtil::Log::write(std::string)
Referenced by HDDTest::TestScenario::run.