HDDTest::ATest
std::string HDDTest::ATest::name
Referenced by ATest.
std::atomic<bool> HDDTest::ATest::isMain
Referenced by ATest, start, HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm, HDDTest::TestScenario::run.
DBUtil::Log* HDDTest::ATest::log
Referenced by ATest, ~ATest, HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm, HDDTest::TestScenario::run.
struct timespec HDDTest::ATest::tv
Referenced by initSleep, sleep.
Relationship* HDDTest::ATest::relationship
Referenced by ATest, HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm, HDDTest::TransactionLog::executeTestAlgorithm.
Disk* HDDTest::ATest::disk
Referenced by ATest, HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm, HDDTest::TransactionLog::executeTestAlgorithm.
std::atomic<bool> HDDTest::ATest::runs
Referenced by ATest, HDDTest::FullTableScan::executeTestAlgorithm, HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm, HDDTest::TransactionLog::executeTestAlgorithm.
HDDTest::ATest::ATest(std::string, Disk *, Relationship *)
References name, disk, relationship, log, runs, isMain, initSleep.
HDDTest::ATest::~ATest()
References log.
void HDDTest::ATest::start()
References isMain, executeTestAlgorithm.
Referenced by startBackground, HDDTest::TestScenario::run.
void HDDTest::ATest::executeTestAlgorithm()
Referenced by start.
void HDDTest::ATest::sleep()
References tv.
Referenced by HDDTest::IndexScan::executeTestAlgorithm, HDDTest::IndexWrite::executeTestAlgorithm, HDDTest::TransactionLog::executeTestAlgorithm.
void HDDTest::ATest::startBackground()
References start.
Referenced by HDDTest::TestScenario::run.
void HDDTest::ATest::initSleep(double)
References tv.
Referenced by ATest, HDDTest::TransactionLog::TransactionLog.