.TH "src/Util/Configurator.cpp" 3 "Mon Nov 10 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Util/Configurator.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Configurator\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBHDDTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
