.TH "src/Util/Configurator.h" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Util/Configurator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rapidjson/document\&.h>\fP
.br
\fC#include <rapidjson/filestream\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include '\&.\&./Tests/TestScenario\&.h'\fP
.br
\fC#include 'Disk\&.h'\fP
.br
\fC#include '\&.\&./Layout/Layout\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHDDTest::Configurator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBHDDTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
