.TH "DBUtil::measurement" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBUtil::measurement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Log\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBduration\fP"
.br
.ti -1c
.RI "uint64_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file Log\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t DBUtil::measurement::duration"

.PP
Definition at line 21 of file Log\&.h\&.
.SS "uint64_t DBUtil::measurement::size"

.PP
Definition at line 22 of file Log\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
