.TH "src/Util/Disk.h" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Util/Disk.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <linux/hdreg\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHDDTest::Disk\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBHDDTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
