.TH "HDDTest::ATest" 3 "Mon Nov 10 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::ATest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ATest\&.h>\fP
.PP
Inherited by \fBHDDTest::FullTableScan\fP, and \fBHDDTest::IndexScan\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBATest\fP (std::string, \fBDisk\fP *, \fBRelationship\fP *)"
.br
.ti -1c
.RI "virtual \fB~ATest\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "virtual void \fBexecuteTestAlgorithm\fP ()"
.br
.ti -1c
.RI "void \fBsleep\fP ()"
.br
.ti -1c
.RI "void \fBstartBackground\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::atomic< bool > \fBisMain\fP"
.br
.ti -1c
.RI "\fBDBUtil::Log\fP * \fBlog\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRelationship\fP * \fBrelationship\fP"
.br
.ti -1c
.RI "\fBDisk\fP * \fBdisk\fP"
.br
.ti -1c
.RI "std::atomic< bool > \fBruns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file ATest\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HDDTest::ATest::ATest (std::stringname, \fBDisk\fP *disk, \fBRelationship\fP *relationship)"

.PP
Definition at line 13 of file ATest\&.cpp\&.
.SS "HDDTest::ATest::~ATest ()\fC [virtual]\fP"

.PP
Definition at line 42 of file ATest\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HDDTest::ATest::executeTestAlgorithm ()\fC [virtual]\fP"

.PP
Reimplemented in \fBHDDTest::FullTableScan\fP, and \fBHDDTest::IndexScan\fP\&.
.PP
Definition at line 40 of file ATest\&.cpp\&.
.SS "void HDDTest::ATest::sleep ()"

.PP
Definition at line 47 of file ATest\&.cpp\&.
.SS "void HDDTest::ATest::start ()"

.PP
Definition at line 23 of file ATest\&.cpp\&.
.SS "void HDDTest::ATest::startBackground ()"

.PP
Definition at line 51 of file ATest\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDisk\fP* HDDTest::ATest::disk\fC [protected]\fP"

.PP
Definition at line 42 of file ATest\&.h\&.
.SS "std::atomic<bool> HDDTest::ATest::isMain"

.PP
Definition at line 31 of file ATest\&.h\&.
.SS "\fBDBUtil::Log\fP* HDDTest::ATest::log"

.PP
Definition at line 38 of file ATest\&.h\&.
.SS "std::string HDDTest::ATest::name"

.PP
Definition at line 30 of file ATest\&.h\&.
.SS "\fBRelationship\fP* HDDTest::ATest::relationship\fC [protected]\fP"

.PP
Definition at line 41 of file ATest\&.h\&.
.SS "std::atomic<bool> HDDTest::ATest::runs\fC [protected]\fP"

.PP
Definition at line 43 of file ATest\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
