.TH "HDDTest::LayoutSettings" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::LayoutSettings \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Layout\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmode\fP"
.br
.ti -1c
.RI "uint64_t \fBpageSizeInKB\fP"
.br
.ti -1c
.RI "uint64_t \fBpagesPerExtent\fP"
.br
.ti -1c
.RI "std::vector< struct 
.br
\fBRelationshipConfig\fP > \fBrelationships\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file Layout\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string HDDTest::LayoutSettings::mode"

.PP
Definition at line 27 of file Layout\&.h\&.
.SS "uint64_t HDDTest::LayoutSettings::pageSizeInKB"

.PP
Definition at line 28 of file Layout\&.h\&.
.SS "uint64_t HDDTest::LayoutSettings::pagesPerExtent"

.PP
Definition at line 29 of file Layout\&.h\&.
.SS "std::vector<struct \fBRelationshipConfig\fP> HDDTest::LayoutSettings::relationships"

.PP
Definition at line 30 of file Layout\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
