.TH "HDDTest" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRelationshipConfig\fP"
.br
.ti -1c
.RI "struct \fBLayoutSettings\fP"
.br
.ti -1c
.RI "class \fBLayout\fP"
.br
.ti -1c
.RI "struct \fBExtent\fP"
.br
.ti -1c
.RI "class \fBRelationship\fP"
.br
.ti -1c
.RI "struct \fBTestSettings\fP"
.br
.ti -1c
.RI "class \fBATest\fP"
.br
.ti -1c
.RI "class \fBFullTableScan\fP"
.br
.ti -1c
.RI "class \fBIndexScan\fP"
.br
.ti -1c
.RI "class \fBIndexWrite\fP"
.br
.ti -1c
.RI "class \fBTestScenario\fP"
.br
.ti -1c
.RI "class \fBTransactionLog\fP"
.br
.ti -1c
.RI "class \fBConfigurator\fP"
.br
.ti -1c
.RI "class \fBDisk\fP"
.br
.ti -1c
.RI "class \fBProgressbar\fP"
.br
.ti -1c
.RI "class \fBRandomizer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDisk\fP manager 
.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
