.TH "HDDTest::Configurator" 3 "Mon Nov 10 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::Configurator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Configurator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigurator\fP ()"
.br
.ti -1c
.RI "virtual \fB~Configurator\fP ()"
.br
.ti -1c
.RI "std::vector< \fBTestScenario\fP * > * \fBgetTestScenarios\fP ()"
.br
.RI "\fIScenario generation based on config file\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file Configurator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HDDTest::Configurator::Configurator ()"

.PP
Definition at line 12 of file Configurator\&.cpp\&.
.SS "HDDTest::Configurator::~Configurator ()\fC [virtual]\fP"

.PP
Definition at line 18 of file Configurator\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBTestScenario\fP * > * HDDTest::Configurator::getTestScenarios ()"

.PP
Scenario generation based on config file\&. Creates scenarios inc\&. test configurations, layouts etc\&. 
.PP
\fBReturns:\fP
.RS 4
vector of test scenarios which can be executed later 
.RE
.PP

.PP
Definition at line 34 of file Configurator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
