.TH "HDDTest::Disk" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::Disk \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Disk\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreadPage\fP (uint64_t)"
.br
.ti -1c
.RI "void \fBreadExtent\fP (uint64_t)"
.br
.ti -1c
.RI "void \fBwritePage\fP (uint64_t)"
.br
.ti -1c
.RI "void \fBwriteExtent\fP (uint64_t)"
.br
.ti -1c
.RI "void \fBdel\fP ()"
.br
.ti -1c
.RI "void \fBsetPageSize\fP (int)"
.br
.RI "\fI[brief description] \fP"
.ti -1c
.RI "void \fBsetExtentSize\fP (int)"
.br
.RI "\fIextent-size-setter \fP"
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.ti -1c
.RI "const std::string & \fBgetPath\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDisk\fP * \fBget\fP (std::string)"
.br
.RI "\fIreturns disk \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBpath\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisValid\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Disk\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void HDDTest::Disk::del ()"

.PP
Definition at line 125 of file Disk\&.cpp\&.
.SS "\fBDisk\fP * HDDTest::Disk::get (std::stringpath)\fC [static]\fP"

.PP
returns disk returns a disk pointer
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP disk path 
.RE
.PP
\fBReturns:\fP
.RS 4
pointer to disk instance 
.RE
.PP

.PP
Definition at line 20 of file Disk\&.cpp\&.
.SS "std::string HDDTest::Disk::getName ()"

.PP
Definition at line 142 of file Disk\&.cpp\&.
.SS "const std::string& HDDTest::Disk::getPath () const\fC [inline]\fP"

.PP
Definition at line 38 of file Disk\&.h\&.
.SS "bool HDDTest::Disk::isValid ()\fC [protected]\fP"

.PP
Definition at line 131 of file Disk\&.cpp\&.
.SS "void HDDTest::Disk::readExtent (uint64_tstart)"

.PP
Definition at line 98 of file Disk\&.cpp\&.
.SS "void HDDTest::Disk::readPage (uint64_tstart)"

.PP
Definition at line 104 of file Disk\&.cpp\&.
.SS "void HDDTest::Disk::setExtentSize (intsize)"

.PP
extent-size-setter sets the extent size in kb
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP Size of a extent in kb 
.RE
.PP

.PP
Definition at line 79 of file Disk\&.cpp\&.
.SS "void HDDTest::Disk::setPageSize (intsize)"

.PP
[brief description] [long description]
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP [description] 
.RE
.PP

.PP
Definition at line 91 of file Disk\&.cpp\&.
.SS "void HDDTest::Disk::writeExtent (uint64_tstart)"

.PP
Definition at line 112 of file Disk\&.cpp\&.
.SS "void HDDTest::Disk::writePage (uint64_tstart)"

.PP
Definition at line 118 of file Disk\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string HDDTest::Disk::path"

.PP
Definition at line 42 of file Disk\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
