.TH "HDDTest::IndexWrite" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::IndexWrite \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IndexWrite\&.h>\fP
.PP
Inherits \fBHDDTest::ATest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexWrite\fP (std::string, \fBDisk\fP *, \fBRelationship\fP *)"
.br
.ti -1c
.RI "virtual \fB~IndexWrite\fP ()"
.br
.ti -1c
.RI "void \fBexecuteTestAlgorithm\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file IndexWrite\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HDDTest::IndexWrite::IndexWrite (std::stringname, \fBDisk\fP *disk, \fBRelationship\fP *relationship)"

.PP
Definition at line 14 of file IndexWrite\&.cpp\&.
.SS "HDDTest::IndexWrite::~IndexWrite ()\fC [virtual]\fP"

.PP
Definition at line 58 of file IndexWrite\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HDDTest::IndexWrite::executeTestAlgorithm ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHDDTest::ATest\fP\&.
.PP
Definition at line 17 of file IndexWrite\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
