.TH "HDDTest::TestSettings" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::TestSettings \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ATest\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::uint64_t \fBsleep\fP"
.br
.ti -1c
.RI "std::string \fBrelationship\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file ATest\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string HDDTest::TestSettings::name"

.PP
Definition at line 22 of file ATest\&.h\&.
.SS "std::string HDDTest::TestSettings::relationship"

.PP
Definition at line 24 of file ATest\&.h\&.
.SS "std::uint64_t HDDTest::TestSettings::sleep"

.PP
Definition at line 23 of file ATest\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
