.TH "HDDTest::Relationship" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::Relationship \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Relationship\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRelationship\fP (std::string, uint64_t, unsigned int, unsigned int)"
.br
.ti -1c
.RI "virtual \fB~Relationship\fP ()"
.br
.ti -1c
.RI "void \fBaddExtent\fP (uint64_t)"
.br
.ti -1c
.RI "int \fBgetProbability\fP (uint64_t)"
.br
.ti -1c
.RI "void \fBsetUnallocatedExtents\fP (uint64_t unallocatedExtents)"
.br
.ti -1c
.RI "uint64_t \fBgetRandomExtent\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetRandomPage\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetNextExtent\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetPrevExtent\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetNextPage\fP ()"
.br
.ti -1c
.RI "bool \fBisNextExtent\fP ()"
.br
.ti -1c
.RI "void \fBsetNextExtent\fP (uint64_t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< struct \fBExtent\fP > \fBextents\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBpagesPerExtent\fP"
.br
.ti -1c
.RI "unsigned int \fBpageSizeInKB\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Relationship\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HDDTest::Relationship::Relationship (std::stringname, uint64_tsize, unsigned intpagesPerExtent, unsigned intpageSizeInKB)"

.PP
Definition at line 13 of file Relationship\&.cpp\&.
.SS "HDDTest::Relationship::~Relationship ()\fC [virtual]\fP"

.PP
Definition at line 23 of file Relationship\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HDDTest::Relationship::addExtent (uint64_tstart)"

.PP
Definition at line 28 of file Relationship\&.cpp\&.
.SS "uint64_t HDDTest::Relationship::getNextExtent ()"

.PP
Definition at line 42 of file Relationship\&.cpp\&.
.SS "uint64_t HDDTest::Relationship::getNextPage ()"

.SS "uint64_t HDDTest::Relationship::getPrevExtent ()"

.PP
Definition at line 57 of file Relationship\&.cpp\&.
.SS "int HDDTest::Relationship::getProbability (uint64_ttotalUnallocatedExtents)"

.PP
Definition at line 76 of file Relationship\&.cpp\&.
.SS "uint64_t HDDTest::Relationship::getRandomExtent ()"

.PP
Definition at line 82 of file Relationship\&.cpp\&.
.SS "uint64_t HDDTest::Relationship::getRandomPage ()"

.PP
Definition at line 87 of file Relationship\&.cpp\&.
.SS "bool HDDTest::Relationship::isNextExtent ()"

.PP
Definition at line 71 of file Relationship\&.cpp\&.
.SS "void HDDTest::Relationship::setNextExtent (uint64_tnextExtent)"

.PP
Definition at line 37 of file Relationship\&.cpp\&.
.SS "void HDDTest::Relationship::setUnallocatedExtents (uint64_tunallocatedExtents)\fC [inline]\fP"

.PP
Definition at line 30 of file Relationship\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<struct \fBExtent\fP> HDDTest::Relationship::extents"

.PP
Definition at line 44 of file Relationship\&.h\&.
.SS "std::string HDDTest::Relationship::name"

.PP
Definition at line 45 of file Relationship\&.h\&.
.SS "unsigned int HDDTest::Relationship::pageSizeInKB"

.PP
Definition at line 48 of file Relationship\&.h\&.
.SS "unsigned int HDDTest::Relationship::pagesPerExtent"

.PP
Definition at line 47 of file Relationship\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
