.TH "HDDTest::FullTableScan" 3 "Mon Nov 10 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::FullTableScan \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHDDTest::ATest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFullTableScan\fP (std::string, \fBDisk\fP *, \fBRelationship\fP *)"
.br
.ti -1c
.RI "virtual \fB~FullTableScan\fP ()"
.br
.ti -1c
.RI "void \fBexecuteTestAlgorithm\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file FullTableScan\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HDDTest::FullTableScan::FullTableScan (std::stringname, \fBDisk\fP *disk, \fBRelationship\fP *relationship)"

.PP
Definition at line 13 of file FullTableScan\&.h\&.
.SS "HDDTest::FullTableScan::~FullTableScan ()\fC [virtual]\fP"

.PP
Definition at line 38 of file FullTableScan\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void HDDTest::FullTableScan::executeTestAlgorithm ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHDDTest::ATest\fP\&.
.PP
Definition at line 18 of file FullTableScan\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
