.TH "HDDTest::RelationshipConfig" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::RelationshipConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Layout\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Layout\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string HDDTest::RelationshipConfig::name"

.PP
Definition at line 21 of file Layout\&.h\&.
.SS "unsigned int HDDTest::RelationshipConfig::size"

.PP
Definition at line 20 of file Layout\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
