.TH "HDDTest::Randomizer" 3 "Mon Nov 17 2014" "DB-Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDDTest::Randomizer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Randomizer\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBseed\fP (uint64_t new_seed=std::mt19937_64::default_seed)"
.br
.ti -1c
.RI "static uint64_t \fBget\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Randomizer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static uint64_t HDDTest::Randomizer::get ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 26 of file Randomizer\&.h\&.
.SS "static void HDDTest::Randomizer::seed (uint64_tnew_seed = \fCstd::mt19937_64::default_seed\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 22 of file Randomizer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DB-Test from the source code\&.
